# 데프만들기 연습

In [5]:
# 모듈로딩
import pandas as pd
import json
import os

In [9]:
# json파일을 데프로 만들기
# 하나의 폴더안의 하나의 시나리오에 대해서만 가능 함수
labelfold='../data/label/'

def json_df_make_test(fold,si_fold):
    accident_df=pd.DataFrame()
    folder_li=[]
    path=labelfold+fold+si_fold

    for file in os.listdir(path):
        a_dic=json.load(open(path+file))
        a_dic_ann=a_dic['annotations']
        if len(a_dic_ann)!=0:
            for _ in range(len(a_dic_ann)):
                folder_li.append(fold.split('/')[0])
            accident_df=pd.concat([accident_df,pd.DataFrame(a_dic_ann)],ignore_index=True)
    accident_df['foldname']=folder_li
    
    return accident_df

In [10]:
acc_87G=json_df_make_test('G/','[emergency]accident11_087G/')
acc_87G

,id,bbox,occluded,num_keypoints,keypoints,action,age,disabled,mask,get_on,get_off,foldname
0,0,"[1061, 330, 1374, 849]",False,16,"[1092, 771, 2, 1101, 648, 2, 1132, 515, 2, 121...",sit down,adult,False,False,False,False,G
1,0,"[1029, 296, 1365, 842]",False,16,"[1092, 765, 2, 1091, 638, 2, 1149, 505, 2, 123...",sit down,adult,False,False,False,False,G
2,0,"[1030, 272, 1311, 858]",False,16,"[1095, 795, 2, 1092, 639, 2, 1137, 495, 2, 122...",sit down,adult,False,False,False,False,G
3,0,"[1019, 275, 1287, 869]",False,16,"[1093, 804, 2, 1083, 657, 2, 1133, 532, 2, 119...",sit down,adult,False,False,False,False,G
4,0,"[1007, 288, 1282, 878]",False,16,"[1092, 809, 2, 1075, 659, 2, 1120, 524, 2, 119...",sit down,adult,False,False,False,False,G
...,...,...,...,...,...,...,...,...,...,...,...,...
88,0,"[978, 372, 1402, 868]",False,16,"[1102, 792, 2, 1092, 743, 2, 1009, 564, 2, 116...",stand,adult,False,False,False,False,G
89,0,"[967, 373, 1391, 860]",False,16,"[1098, 777, 2, 1095, 730, 2, 1014, 555, 2, 110...",stand,adult,False,False,False,False,G
90,0,"[967, 373, 1391, 860]",False,16,"[1098, 777, 2, 1095, 730, 2, 1014, 555, 2, 110...",stand,adult,False,False,False,False,G
91,0,"[1024, 358, 1380, 858]",False,16,"[1101, 773, 2, 1099, 688, 2, 1085, 538, 2, 118...",stand,adult,False,False,False,False,G
92,0,"[1024, 356, 1380, 856]",False,16,"[1101, 771, 2, 1099, 686, 2, 1105, 492, 2, 121...",sit down,adult,False,False,False,False,G

In [11]:
# json파일에 2명의 사람에 대한 데이터가 모두 행으로 변환되는지 확인용
a_dic=json.load(open('C:/Users/USER/Desktop/com_project/data/label/E/[emergency]accident12_055E/[emergency]accident12_055E_790.json'))
pd.DataFrame(a_dic['annotations'])

,id,bbox,occluded,num_keypoints,keypoints,action,age,disabled,mask,get_on,get_off
0,0,"[418, 673, 933, 1079]",True,16,"[575, 1079, 0, 575, 982, 0, 864, 978, 2, 805, ...",walk,adult,False,False,False,False
1,1,"[253, 826, 825, 1079]",True,16,"[517, 1027, 0, 517, 963, 0, 517, 899, 0, 134, ...",walk,adult,False,False,False,False

In [6]:
# json파일을 데프로 만들기 함수
# 알파벳은 각각의 카메라를 의미
action_str=['stand','walk','run','sit down','lay down','grab handle','kick','punch']
get_str=['get_off','get_on','nothing']

def json_df_make(fold):
    accident_df=pd.DataFrame()
    folder_li=[]
    json_name_li=[]
    action_int=[]
    get_int=[]

    for f in fold:
        path=labelfold+f
        for si_fo in os.listdir(path):
            files=path+si_fo+'/'
            for file in os.listdir(files):
                accident_dic=json.load(open(files+file))
                accident_dic_ann=accident_dic['annotations']
                if len(accident_dic_ann)!=0:
                    for i in range(len(accident_dic_ann)):
                        # 폴더명(카메라)
                        folder_li.append(f.split('/')[0])

                        # 파일명
                        json_name_li.append(file)

                        # 액션
                        if accident_dic_ann[i]['action']=='stand':
                            action_int.append(0)
                        elif accident_dic_ann[i]['action']=='walk':
                            action_int.append(1)
                        elif accident_dic_ann[i]['action']=='run':
                            action_int.append(2)
                        elif accident_dic_ann[i]['action']=='sit down':
                            action_int.append(3)
                        elif accident_dic_ann[i]['action']=='lay down':
                            action_int.append(4)
                        elif accident_dic_ann[i]['action']=='grab handle':
                            action_int.append(5)
                        elif accident_dic_ann[i]['action']=='kick':
                            action_int.append(6)
                        else:
                            action_int.append(7)
                        
                        # 승하차
                        if ((accident_dic_ann[i]['get_on']==False) & (accident_dic_ann[i]['get_off']==False)):
                            get_int.append(2)
                        elif accident_dic_ann[i]['get_on']==True:
                            get_int.append(1)
                        elif accident_dic_ann[i]['get_off']==True:
                            get_int.append(0)
                        else:
                            get_int.append(4)
                accident_df=pd.concat([accident_df,pd.DataFrame(accident_dic_ann)],ignore_index=True)

    accident_df['foldname']=folder_li # 카메라의 알파벳을 새로운 열로 추가
    accident_df['json_name']=json_name_li
    accident_df['action_int']=action_int
    accident_df['get_int']=get_int

    # boolean값 인수형으로 바꾸기
    accident_df.occluded=[1 if b==True else 0 for b in accident_df.occluded]
    accident_df.disabled=[1 if b==True else 0 for b in accident_df.disabled]
    accident_df['mask']=[1 if b==True else 0 for b in accident_df['mask']]

    # 필요없는 열 삭제
    accident_df=accident_df.drop(['get_on','get_off'],axis=1)

    return accident_df

In [7]:
# 사고 train json파일
labelfold='../json/[라벨]Emergency_train_accident/'
tra_accident_df=json_df_make(['A/','B/','C/','D/','E/','F/','G/','H/'])

In [8]:
tra_accident_df

,id,bbox,occluded,num_keypoints,keypoints,action,age,disabled,mask,foldname,json_name,action_int,get_int
0,0,"[681, 436, 1470, 1075]",1,16,"[821, 1075, 0, 740, 986, 1, 979, 1014, 2, 1292...",sit down,adult,0,0,A,[emergency]accident07_001A_0.json,3,2
1,1,"[891, 147, 1007, 554]",1,16,"[945, 515, 2, 936, 433, 2, 933, 344, 2, 973, 3...",stand,adult,0,0,A,[emergency]accident07_001A_0.json,0,2
2,1,"[891, 147, 1007, 554]",1,16,"[945, 515, 2, 936, 433, 2, 933, 344, 2, 973, 3...",stand,adult,0,0,A,[emergency]accident07_001A_10.json,0,2
3,0,"[681, 420, 1470, 1075]",1,16,"[821, 1075, 0, 740, 983, 1, 979, 1012, 2, 1292...",sit down,adult,0,0,A,[emergency]accident07_001A_10.json,3,2
4,1,"[711, 162, 1026, 1034]",1,16,"[814, 1024, 1, 842, 844, 1, 831, 665, 2, 921, ...",walk,adult,0,0,A,[emergency]accident07_001A_100.json,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
21571,0,"[998, 181, 1347, 763]",1,16,"[1084, 660, 2, 1089, 601, 2, 1098, 485, 2, 116...",grab handle,adult,0,0,H,[emergency]accident11_086H_70.json,5,2
21572,0,"[975, 192, 1334, 760]",1,16,"[1159, 648, 2, 1178, 535, 2, 1080, 465, 2, 114...",walk,adult,0,0,H,[emergency]accident11_086H_80.json,1,2
21573,0,"[1043, 216, 1330, 760]",1,16,"[1116, 695, 2, 1148, 583, 2, 1101, 496, 2, 115...",grab handle,adult,0,0,H,[emergency]accident11_086H_90.json,5,2
21574,0,"[584, 563, 1049, 1078]",1,16,"[759, 1020, 0, 808, 946, 0, 811, 824, 0, 712, ...",walk,adult,0,0,H,[emergency]accident11_086H_980.json,1,2
21575,0,"[802, 429, 1190, 1079]",1,16,"[1059, 1019, 2, 1059, 961, 2, 1052, 916, 2, 87...",walk,adult,0,0,H,[emergency]accident11_086H_990.json,1,2

In [63]:
# 폭행 train json파일
labelfold='../json/[라벨]Emergency_train_violence/'
tra_violence_df=json_df_make(['A/','B/','C/','D/','E/','F/','G/','H/'])

In [64]:
# 사고 validation json파일
labelfold='../json/[라벨]Emergency_val_accident/'
val_accident_df=json_df_make(['A/','B/','C/','D/','E/','F/','G/','H/'])

In [65]:
# 폭행 validation json파일
labelfold='../json/[라벨]Emergency_val_violence/'
val_violence_df=json_df_make(['A/','B/','C/','D/','E/','F/','G/','H/'])

In [66]:
# 통합 json파일
action_dect_df=pd.concat([tra_accident_df, tra_violence_df, val_accident_df, val_violence_df],axis=0,ignore_index=True)
action_dect_df

,id,bbox,occluded,num_keypoints,keypoints,action,age,disabled,mask,foldname,json_name,action_int,get_int
0,0,"[681, 436, 1470, 1075]",1,16,"[821, 1075, 0, 740, 986, 1, 979, 1014, 2, 1292...",sit down,adult,0,0,A,[emergency]accident07_001A_0.json,3,2
1,1,"[891, 147, 1007, 554]",1,16,"[945, 515, 2, 936, 433, 2, 933, 344, 2, 973, 3...",stand,adult,0,0,A,[emergency]accident07_001A_0.json,0,2
2,1,"[891, 147, 1007, 554]",1,16,"[945, 515, 2, 936, 433, 2, 933, 344, 2, 973, 3...",stand,adult,0,0,A,[emergency]accident07_001A_10.json,0,2
3,0,"[681, 420, 1470, 1075]",1,16,"[821, 1075, 0, 740, 983, 1, 979, 1012, 2, 1292...",sit down,adult,0,0,A,[emergency]accident07_001A_10.json,3,2
4,1,"[711, 162, 1026, 1034]",1,16,"[814, 1024, 1, 842, 844, 1, 831, 665, 2, 921, ...",walk,adult,0,0,A,[emergency]accident07_001A_100.json,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43901,1,"[611, 747, 1188, 1077]",1,16,"[997, 1077, 0, 997, 1010, 0, 1016, 1042, 0, 88...",walk,adult,0,0,H,[emergency]violence06_036H_550.json,1,2
43902,1,"[1189, 319, 1581, 720]",1,16,"[1458, 636, 1, 1483, 581, 1, 1494, 658, 1, 141...",sit down,adult,0,0,H,[emergency]violence06_036H_60.json,3,2
43903,1,"[1177, 288, 1569, 716]",1,16,"[1446, 632, 1, 1471, 577, 1, 1482, 654, 1, 139...",sit down,adult,0,0,H,[emergency]violence06_036H_70.json,3,2
43904,1,"[1163, 250, 1488, 716]",1,16,"[1373, 670, 1, 1372, 585, 1, 1418, 523, 2, 133...",stand,adult,0,0,H,[emergency]violence06_036H_80.json,0,2
43905,1,"[1145, 161, 1458, 715]",1,16,"[1331, 670, 1, 1337, 561, 1, 1381, 437, 1, 129...",stand,adult,0,0,H,[emergency]violence06_036H_90.json,0,2

In [67]:
# csv파일 만들기
action_dect_df.to_csv('action_dect_df.csv',index=False,encoding='cp949')